version: "3"

services:

  auth:
    container_name: auth
    build: ./auth
    ports: 
      - 4001:8080
    volumes:
      - ./.env:/app/.env
    restart: always
    networks:
      - golangjwt

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5000:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - golangjwt

networks:
  golangjwt:
    driver: bridge
